### ISSUE TITLE
Does this adapter work?

### ISSUE THREAD

**Issue by GermanBluefox** [soef/ioBroker.hid#1]
Can I include it into repository?

**Comment by soef** [comment]
Hi, I think the iobroker.hid Adapter is already in the repository. Isn't it?

**Comment by GermanBluefox** [comment]
Yes. Hid is in repo. Some people say, it does not work:(

But no logs... so ignore it.

пн, 26 мар. 2018 г., 18:43 Soef <notifications@github.com>:
